version: "3.9"

services:
  app:
    image: martijnvcit/jobly-jobs:0.1.0
    ports:
      - "8090:8090"

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${DATABASE_NAME_JOBS}
      SPRING_DATASOURCE_USERNAME: ${SQL_ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_ADMIN_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
