spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}